name = "mailcheck"
main = "src/index.ts"
compatibility_date = "2024-12-01"
workers_dev = true

routes = [
  { pattern = "mailcheck.bensontech.dev", custom_domain = true }
]

[observability]
enabled = true
